WIP: Chapter 9.2. Problems For Champions
SoftUni/Programming-Basics-Book-Python-BG pull request #1
Opened 2018-06-16 16:30 UTC by Teodor92

2018-07-18 07:47 UTC, miglen requested changes
Моля адресирай коментарите в ревюто.

2018-07-18 07:47 UTC, miglen commented on chapter-09-problems-for-champions-part-2.md
> +Нека разгледаме първите два проблема пред нашия алгоритъм. Първият проблем засяга начина, по който можем да четем командите, докато не срещнем **"mall.Exit"**. Решението, както видяхме по-горе, е да
моля адресирай mall.Exit трябва да е exit()

2018-07-18 07:47 UTC, miglen commented on chapter-09-problems-for-champions-part-2.md
> +- Ако нашият символ е **цифра**, тогава трябва да **променим текущия резултат от израза в зависимост от текущия оператор**, т.е. ако **`expressionOperator`** е **`-`**, тогава трябва да **намалим рез
Погледни expressionOperator. Дори да е променлива трябва да е питонски формат expression_operator

2018-07-18 07:47 UTC, miglen commented on chapter-09-problems-for-champions-part-2.md
> +Тествайте решението си тук: [https://judge.softuni.bg/Contests/Practice/Index/519#2](https://judge.softuni.bg/Contests/Practice/Index/1062#2).
Тук самият линк все още е 519, промени го на 1062.

2018-07-20 11:45 UTC, vncpetrov commented
Картинките не са ОК

2018-07-21 16:53 UTC, Teodor92 commented on chapter-09-problems-for-champions-part-2.md
> +Нека разгледаме първите два проблема пред нашия алгоритъм. Първият проблем засяга начина, по който можем да четем командите, докато не срещнем **"mall.Exit"**. Решението, както видяхме по-горе, е да
Защо? Има промяна в условието на задачата?

2018-07-21 16:53 UTC, Teodor92 commented on chapter-09-problems-for-champions-part-2.md
> +- Ако нашият символ е **цифра**, тогава трябва да **променим текущия резултат от израза в зависимост от текущия оператор**, т.е. ако **`expressionOperator`** е **`-`**, тогава трябва да **намалим рез
Да - поправих naming convention-a навякъде и сега ще обновя всички картинки

2018-07-21 17:21 UTC, Teodor92 commented
Изображенията са обновени с новия размер на фонт и навите правила за именуване, Кометнарите са адресирани, освен този за промяна на mall.Exit - @vncpetrov @miglen

2018-07-26 09:05 UTC, miglen commented on chapter-09-problems-for-champions-part-2.md
> +Нека разгледаме първите два проблема пред нашия алгоритъм. Първият проблем засяга начина, по който можем да четем командите, докато не срещнем **"mall.Exit"**. Решението, както видяхме по-горе, е да
Моя грешка, реших че идва от C#

2018-08-07 13:11 UTC, vncpetrov commented
Един тест от примерното решение за задача 01. Passion Days файлва.
Test case:
**79228162514264337593543950335
mall.Enter
%%%%%%%%%%JHZJHJZKLZ
!@#$%^&())%%%%%%%%%%
(&^%$#@!%%%%%%%%%%%%
)(&^%$#@#$%^&(******
<><<><><><><>[][][][
ABCDEFGHIJKLMNO}}}}}
PQRSTUVWXYZ{{{{{{{{{
abcdefghijkl()()()()
mnopqrstuvwjdkajsfdk
xyz1234567890DAJSHJA
1234567890ASLKDJAKJD
ABCDEFGHIJKLMNOUDSAD
PQRSTUVWXYZ987987988
abcdefghijkl12345676
mnopqrstuvw  HJHJDSD
xyz1234567890&*&^%^$
1234567890hdkjashkdd
hjk;jhdajksdhsakldla
mall.Exit
%%%%**

Expected:
**353 purchases. Money left: 576460752303416096.37 lv.**

Actual:
**353 purchases. Money left: 576460752303420544.00 lv.**

2018-10-09 08:02 UTC, merged