Chapter 05 loops
SoftUni/Programming-Basics-Book-Python-BG pull request #10
Opened 2018-07-21 15:00 UTC by mdamyanova

I think I'm done with my chapter. Let me know if there is something to fix.

2018-07-23 07:58 UTC, miglen requested changes
Линковете към задачите водят към стара група, а трябва да бъдат към: https://judge.softuni.bg/Contests/Practice/Index/1053
Картинките на мен ми изглеждат окей.
Бих посъветвал да смачкаш комитите (squash commits). 👍

2018-07-23 07:58 UTC, miglen commented on chapter-05-loops.md
> +Тествайте решението си тук: [https://judge.softuni.bg/Contests/Practice/Index/154#0](https://judge.softuni.bg/Contests/Practice/Index/154#0).
https://judge.softuni.bg/Contests/Practice/Index/1053#0

2018-07-23 07:58 UTC, miglen commented on chapter-05-loops.md
> +Тествайте решението си тук: [https://judge.softuni.bg/Contests/Practice/Index/154#1](https://judge.softuni.bg/Contests/Practice/Index/154#1).
https://judge.softuni.bg/Contests/Practice/Index/1053#1

2018-07-23 07:58 UTC, miglen commented on chapter-05-loops.md
> +Тествайте решението си тук: [https://judge.softuni.bg/Contests/Practice/Index/154#3](https://judge.softuni.bg/Contests/Practice/Index/154#3).
https://judge.softuni.bg/Contests/Practice/Index/1053#3

2018-07-23 07:58 UTC, miglen commented on chapter-05-loops.md
> +Тествайте решението си тук: [https://judge.softuni.bg/Contests/Practice/Index/154#7](https://judge.softuni.bg/Contests/Practice/Index/154#7).
https://judge.softuni.bg/Contests/Practice/Index/1053#7

2018-07-23 07:58 UTC, miglen commented on chapter-05-loops.md
> +Тествайте решението си тук: [https://judge.softuni.bg/Contests/Practice/Index/154#6](https://judge.softuni.bg/Contests/Practice/Index/154#6).
https://judge.softuni.bg/Contests/Practice/Index/1053#6

2018-07-23 07:58 UTC, miglen commented on chapter-05-loops.md
> +Тествайте решението си тук: [https://judge.softuni.bg/Contests/Practice/Index/154#5](https://judge.softuni.bg/Contests/Practice/Index/154#5).
https://judge.softuni.bg/Contests/Practice/Index/1053#5

2018-07-23 07:58 UTC, miglen commented on chapter-05-loops.md
> +Тествайте решението си тук: [https://judge.softuni.bg/Contests/Practice/Index/154#9](https://judge.softuni.bg/Contests/Practice/Index/154#9).
https://judge.softuni.bg/Contests/Practice/Index/1053#9

2018-07-23 07:58 UTC, miglen commented on chapter-05-loops.md
> +Тествайте решението си тук: [https://judge.softuni.bg/Contests/Practice/Index/154#10](https://judge.softuni.bg/Contests/Practice/Index/154#10).
https://judge.softuni.bg/Contests/Practice/Index/1053#10

2018-07-23 07:58 UTC, miglen commented on chapter-05-loops.md
> +Тествайте решението си тук: [https://judge.softuni.bg/Contests/Practice/Index/154#11](https://judge.softuni.bg/Contests/Practice/Index/154#11).
https://judge.softuni.bg/Contests/Practice/Index/1053#11

2018-07-23 09:40 UTC, mdamyanova commented
Готова съм с линковете. Разгледах за squash commits, но не смея да пробвам, налага ли се, ще излизат ли комитите след като се мерджне?

2018-07-23 09:45 UTC, miglen commented
Не се страхувай от това, мисля че ще излезнат не е критично. Ако искаш да е safe, направи си нов branch от текущия за бекъп (git checkout -b chapter-05-loops-bkk) И след това си направи squash на всички промени в един. Препоръчвам и следното наименоване на отделните commits - https://chris.beams.io/posts/git-commit/ 
За мен не е голям проблем, просто е по-подредено.

2018-07-23 10:09 UTC, mdamyanova commented
Сега? :)

2018-07-26 09:02 UTC, miglen approved these changes

2018-10-09 08:42 UTC, merged