Chapter 07 complex loops exam problems
SoftUni/Programming-Basics-Book-Python-BG pull request #11
Opened 2018-07-22 22:09 UTC by Antoveravip

Done. Ready for check and merge.

2018-07-23 07:52 UTC, miglen requested changes
assets/chapter-7-2-images/01.stupid-password-generator-2.png - шрифта изглежда много малък докато assets/chapter-7-2-images/01.stupid-password-generator-3.png изглежда много голям.

Освен картинките, не само тези горе но и останалите ми се виждат с различна големина останалото е окей. Също забелязах, че ползваш tabs вместо spaces, според pep8 те са предпочитани моля те промени особено големите картинки със spaces като stupid password generator 2.png

2018-07-23 17:04 UTC, Antoveravip commented
Странно как ти се виждат различни, когато са с еднакъв шрифт. :( но ще ги погледна пак. 
Ще заменя табовете със спейсове и ще ги снимам наново.

2018-07-23 17:17 UTC, Antoveravip commented
Помежду другото не съм и използвал табове, а спейсове. Може да видиш файловете и кода и да ги отвориш в Notepad++ примерно и да избереш да се виждат всички всички символи.
Ще погледна отново шрифта и ще ги направя наново снимките - за всеки случай, макар, че се съмнявам да има разлика.

2018-07-23 19:17 UTC, Antoveravip commented
Done. Изглежда проблема идваше от широчината на определени снимки и се получаваше auto-resize, който намаляваше визуално снимката. Вече всичко би трябвало да е наред.

2018-07-24 11:53 UTC, miglen approved these changes

2018-10-09 07:50 UTC, merged